
- name: update_cache....
  apt:
   update_cache: yes
  become: yes

- name: Install LAMP
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ package_name }}"

- name: Démarrer appache2 et mysql
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - apache2
    - mysql      

